const fs = require('fs');
const path = require('path');

const generateSidebar = () => {
  const sidebar = {
    tutorialSidebar: [],
  };

  const docsDir = path.join(__dirname, '../docs');

  const categoryDirs = fs.readdirSync(docsDir).filter(file =>
    fs.lstatSync(path.join(docsDir, file)).isDirectory()
  );

  // Add categories to the sidebar
  categoryDirs.forEach(dir => {
    const categoryFilePath = path.join(docsDir, dir, 'category.json');

    if (fs.existsSync(categoryFilePath)) {
      const categoryData = JSON.parse(fs.readFileSync(categoryFilePath, 'utf8'));
      sidebar.tutorialSidebar.push({
        type: 'category',
        label: categoryData.label,
        link: { type: 'generated-index' },
        items: [{ type: 'autogenerated', dirName: dir }],
      });
    }
  });

  const rootDocs = fs
    .readdirSync(docsDir)
    .filter(file => file.endsWith('.md') && file !== 'index.md');

  rootDocs.forEach(doc => {
    sidebar.tutorialSidebar.push({
      type: 'doc',
      id: doc.replace('.md', ''), // Use filename without .md extension
    });
  });

  const sidebarPath = path.join(__dirname, '../sidebars.js');
  fs.writeFileSync(
    sidebarPath,
    `module.exports = ${JSON.stringify(sidebar, null, 2)};`,
    'utf8'
  );

  console.log('Sidebar generated successfully');
};

// Generate the sidebar
generateSidebar();
